apiVersion: v1
kind: Service
metadata:
  labels:
    service: capstone-frontend
  name: capstone-frontend
spec:
  ports:
  - name: "8100"
    port: 8100
    targetPort: 80
  selector:
    service: capstone-frontend
#  type: LoadBalancer    
